In [6]:
import numpy  as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('energydata_complete.csv')

In [8]:
df.head()

Normalizing Dataset

In [27]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dropped_df = df.drop(columns=["date","lights"])
normalised_dropped_df = DataFrame(scaler.fit_transform(dropped_df),columns = dropped_df.columns)
independent_variable = normalised_dropped_df.drop(columns =["Appliances"])
target_variable = normalised_dropped_df["Appliances"]


In [99]:
#normalised_dropped_df
#independent_variable
#target_variable

SPLITING DATASET INTO TEST AND TRAIN 

In [28]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(independent_variable,target_variable,test_size = 0.3,random_state = 42)


SIMPLE LINEAR REGRESSION

In [29]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
y_pred = regressor.predict(x_test)
y_pred.reshape(-1,1)

array([[0.03322207],
       [0.24411599],
       [0.03400024],
       ...,
       [0.06844707],
       [0.10032325],
       [0.05722198]])

GETTING WEIGHTS FOR LINEAR_MODEL

In [31]:
def get_weight(model,feat,col_name):
    weights = Series(model.coef_,feat.columns).sort_values()
    weights = DataFrame(weights).reset_index()
    weights.columns = ["Features",col_name]
    weights[col_name].round(3)
    return weights


LASSO REGRESSION

In [36]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha = 0.001)
lasso_reg.fit(x_train,y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [39]:
y_lasso_pred = lasso_reg.predict(x_test)
y_lasso_pred.reshape(-1,1)

array([[0.07370267],
       [0.08143458],
       [0.07716072],
       ...,
       [0.07792848],
       [0.09034412],
       [0.08359255]])

In [44]:
y_ridge_pred = ridge_reg.predict(x_test)
y_ridge_pred.reshape(-1,1)

array([[0.03321872],
       [0.24043824],
       [0.03461337],
       ...,
       [0.06872351],
       [0.10025536],
       [0.05851175]])

RIDGE REGRESSION

In [43]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha = 0.4)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

LINEAR REGRESSION

In [33]:
linear_reg = LinearRegression()
linear_reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

COMPUTING THE WEIGHTS

LINEAR MODEL

In [35]:
linear_model_weights = get_weight(linear_reg,x_train,'Linear_model_weight')
linear_model_weights

MEAN ABSOLUTE ERROR

In [47]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
round(mae, 2)

0.05

R SQUARED VALUE

In [46]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, y_pred)
round(r2_score, 2)

0.15

RESIDUAL SUM OF SQUARES

In [48]:
rss = np.sum(np.square(y_test - y_pred))
round(rss, 2)

45.35

ROOT MEAN SQUARE

In [45]:
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_ridge_pred))
round(rmse, 3) 	

0.088